window.FC_DECKS = {
  'kinematics': {
    title: 'Kinematics',
    back: '../kinematics/',
    cards: [
      { q: 'Average velocity',                              a: '\\[v = \\dfrac{\\Delta x}{\\Delta t}\\]',
        desc: '\\(\\Delta x\\) = displacement &nbsp;·&nbsp; \\(\\Delta t\\) = elapsed time<br><br><strong>In words:</strong> average velocity tells how quickly position changes, including the direction of that change.' },
      { q: 'Average acceleration',                          a: '\\[a = \\dfrac{\\Delta v}{\\Delta t}\\]',
        desc: '\\(\\Delta v\\) = change in velocity &nbsp;·&nbsp; \\(\\Delta t\\) = elapsed time<br><br><strong>In words:</strong> average acceleration tells how quickly velocity changes over a time interval.' },
      { q: 'Kinematic eq. &#x2014; missing \\(x\\)',        a: '\\[v = v_0 + at\\]',
        desc: '\\(v_0\\) = initial velocity &nbsp;·&nbsp; \\(a\\) = acceleration &nbsp;·&nbsp; \\(t\\) = time<br><br><strong>In words:</strong> final velocity equals the starting velocity plus the velocity gained from constant acceleration.' },
      { q: 'Kinematic eq. &#x2014; missing \\(v\\)',        a: '\\[x = x_0 + v_0 t + \\tfrac{1}{2}at^2\\]',
        desc: '\\(x_0\\) = initial position &nbsp;·&nbsp; \\(v_0\\) = initial velocity &nbsp;·&nbsp; \\(a\\) = constant acceleration<br><br><strong>In words:</strong> position combines where the object started, motion from its initial velocity, and extra motion caused by acceleration.' },
      { q: 'Kinematic eq. &#x2014; missing \\(t\\)',        a: '\\[v^2 = v_0^2 + 2a(x - x_0)\\]',
        desc: '\\(v\\) = final velocity &nbsp;·&nbsp; \\(v_0\\) = initial velocity &nbsp;·&nbsp; \\(a\\) = acceleration &nbsp;·&nbsp; \\(\\Delta x\\) = displacement<br><br><strong>In words:</strong> this connects speed and displacement under constant acceleration without needing time.' },
      { q: 'Kinematic eq. &#x2014; missing \\(a\\)',        a: '\\[x - x_0 = \\tfrac{1}{2}(v_0 + v)\\,t\\]',
        desc: '\\(v_0\\) = initial velocity &nbsp;·&nbsp; \\(v\\) = final velocity &nbsp;·&nbsp; \\(t\\) = time<br><br><strong>In words:</strong> under constant acceleration, displacement equals average velocity multiplied by elapsed time.' },
      { q: 'Vector components',                             a: '\\[v_x = v\\cos\\theta \\qquad v_y = v\\sin\\theta\\]',
        desc: '\\(v\\) = vector magnitude &nbsp;·&nbsp; \\(\\theta\\) = angle from the positive x-axis<br><br><strong>In words:</strong> vector components split one angled vector into independent horizontal and vertical parts.' },
      { q: 'Resultant magnitude and angle',                 a: '\\[v = \\sqrt{v_x^2 + v_y^2} \\qquad \\theta = \\tan^{-1}\\!\\left(\\dfrac{v_y}{v_x}\\right)\\]',
        desc: '\\(v_x\\) = horizontal component &nbsp;·&nbsp; \\(v_y\\) = vertical component &nbsp;·&nbsp; \\(\\theta\\) = direction angle<br><br><strong>In words:</strong> perpendicular components combine to recover a vector\'s total size and direction.' },
      { q: 'Projectile motion: horizontal',                 a: '\\[v_x = v_{x0} \\qquad x = x_0 + v_{x0}\\,t\\]',
        desc: '\\(v_{x0}\\) = initial horizontal velocity &nbsp;·&nbsp; \\(t\\) = elapsed time<br><br><strong>In words:</strong> without air resistance, a projectile moves horizontally at constant velocity.' },
      { q: 'Projectile motion: vertical',                   a: '\\[v_y = v_{y0} - gt \\qquad y = y_0 + v_{y0}\\,t - \\tfrac{1}{2}gt^2\\]',
        desc: '\\(g \\approx 9.8\\) m/s² downward &nbsp;·&nbsp; \\(v_{y0}\\) = initial vertical velocity<br><br><strong>In words:</strong> gravity continuously changes a projectile\'s vertical velocity and bends its path downward.' },
      { type: 'tf', q: 'An object with zero acceleration must be at rest.',
        a: 'False. Zero acceleration means constant velocity, which can be any value including nonzero.' },
      { type: 'tf', q: 'The slope of a velocity-time graph gives acceleration.',
        a: 'True. \\(a = \\Delta v / \\Delta t\\) is the rise-over-run of the \\(v\\)-\\(t\\) graph.' },
      { type: 'tf', q: 'A projectile at its highest point has zero acceleration.',
        a: 'False. Vertical velocity is zero at the peak, but acceleration is still \\(g\\) downward throughout the flight.' },
      { type: 'tf', q: 'An object can have velocity and acceleration pointing in opposite directions.',
        a: 'True. This simply means the object is slowing down (e.g., a ball thrown upward on the way up).' },
      { q: 'Vertical kinematic eq. &#x2014; missing \\(t\\)',  a: '\\[v_y^2 = v_{y0}^2 - 2g\\,\\Delta y\\]',
        desc: '\\(v_y\\) = final vertical velocity &nbsp;·&nbsp; \\(v_{y0}\\) = initial vertical velocity &nbsp;·&nbsp; \\(\\Delta y\\) = vertical displacement<br><br><strong>In words:</strong> this connects vertical speed and height change under gravity without needing time.' },
      { type: 'tf', q: 'The displacement of an object always equals the total distance it travels.',
        a: 'False. Distance is total path length (scalar); displacement is the net change in position (vector). They match only when motion is in one direction without backtracking.' },
      { type: 'tf', q: 'The area under a velocity–time graph equals the object\'s displacement.',
        a: 'True. By definition \\(\\Delta x = \\int v\\,dt\\), which is the area under the \\(v\\)-\\(t\\) curve.' },
      { type: 'tf', q: 'For a projectile launched horizontally, the time of flight depends on the launch speed.',
        a: 'False. Hang time depends only on vertical free fall: \\(h = \\tfrac{1}{2}gt^2\\). Horizontal speed affects range, not flight time.' },
      { type: 'tf', q: 'At the peak of a projectile\'s trajectory, only the vertical component of velocity is zero.',
        a: 'True. \\(v_y = 0\\) at the peak, but horizontal velocity \\(v_x = v_{x0}\\) remains unchanged throughout.' },
      { type: 'tf', q: 'The slope of a position–time graph at any point gives the instantaneous velocity at that moment.',
        a: 'True. Instantaneous velocity is the derivative of position with respect to time, which equals the tangent slope of the \\(x\\)-\\(t\\) graph.' },
      { type: 'tf', q: 'An object can have a constant speed while its velocity is changing.',
        a: 'True. Velocity is a vector; if direction changes (e.g., circular motion), velocity changes even when speed stays constant.' },
      { type: 'tf', q: 'In a vacuum, two objects of different masses dropped from the same height hit the ground at the same time.',
        a: 'True. Free-fall acceleration \\(g\\) is independent of mass, so both experience the same \\(g\\) and fall identically.' },
      { type: 'tf', q: 'If an object returns to its starting point, its displacement is zero but distance traveled may not be.',
        a: 'True. Displacement is the net vector from start to finish — zero for a round trip. Distance is total path length, which is nonzero.' },
    ]
  },
  'dynamics': {
    title: 'Dynamics',
    back: '../force-dynamics/',
    cards: [
      { q: "Newton's 1st law",                              a: '\\[\\textstyle\\sum \\vec{F} = 0 \\iff \\vec{a} = 0\\]',
        desc: '\\(\\sum\\vec{F}\\) = net force &nbsp;·&nbsp; \\(\\vec{a}\\) = acceleration<br><br><strong>In words:</strong> without a net force, an object keeps its current velocity, including remaining at rest.' },
      { q: "Newton's 2nd law",                              a: '\\[\\textstyle\\sum \\vec{F} = m\\vec{a}\\]',
        desc: '\\(\\sum\\vec{F}\\) = net force &nbsp;·&nbsp; \\(m\\) = mass (kg) &nbsp;·&nbsp; \\(\\vec{a}\\) = acceleration (m/s²)<br><br><strong>In words:</strong> net force produces acceleration, while greater mass makes the same force less effective.' },
      { q: "Newton's 3rd law",                              a: '\\[\\vec{F}_{A \\to B} = -\\vec{F}_{B \\to A}\\]',
        desc: '\\(\\vec{F}_{A\\to B}\\) = force of A on B &nbsp;·&nbsp; \\(\\vec{F}_{B\\to A}\\) = force of B on A<br><br><strong>In words:</strong> interacting objects push or pull each other equally in opposite directions.' },
      { q: 'Component form of the 2nd law',                 a: '\\[\\textstyle\\sum F_x = ma_x \\qquad \\sum F_y = ma_y\\]',
        desc: '\\(F_x,F_y\\) = force components &nbsp;·&nbsp; \\(a_x,a_y\\) = acceleration components<br><br><strong>In words:</strong> Newton\'s second law can be solved separately in each perpendicular direction.' },
      { q: 'Center of mass',                                a: '\\[x_{\\text{cm}} = \\dfrac{\\sum m_i\\, x_i}{\\sum m_i}\\]',
        desc: '\\(m_i\\) = mass of particle \\(i\\) &nbsp;·&nbsp; \\(x_i\\) = its position<br><br><strong>In words:</strong> the center of mass is the mass-weighted average position of a system.' },
      { type: 'tf', q: 'Two objects with the same net force always have the same acceleration.',
        a: 'False. Acceleration also depends on mass: \\(a = F/m\\). Same force on a heavier object gives less acceleration.' },
      { type: 'tf', q: 'An object moving at constant velocity has zero net force acting on it.',
        a: "True. Newton's 1st law: constant velocity (including constant zero) requires \\(\\sum \\vec{F} = 0\\)." },
      { type: 'tf', q: "Newton's 3rd law force pairs act on the same object.",
        a: 'False. They always act on two different objects: if A pulls B, B pulls A with equal force in the opposite direction.' },
      { q: 'Two-body center of mass',                         a: '\\[x_{\\text{cm}} = \\dfrac{m_1 x_1 + m_2 x_2}{m_1 + m_2}\\]',
        desc: '\\(m_1,m_2\\) = masses &nbsp;·&nbsp; \\(x_1,x_2\\) = positions<br><br><strong>In words:</strong> the balance point of two masses lies closer to the heavier object.' },
      { type: 'tf', q: 'The center of mass of two unequal masses lies at the geometric midpoint between them.',
        a: 'False. The center of mass is closer to the heavier mass. It is at the midpoint only when the masses are equal.' },
      { type: 'tf', q: 'An object in translational equilibrium must be at rest.',
        a: 'False. Equilibrium means zero net force, which means zero acceleration. An object moving at constant velocity is also in equilibrium.' },
      { type: 'tf', q: 'If the net force on an object is zero, every individual force acting on it must be zero.',
        a: 'False. Multiple nonzero forces can sum to zero net force. A book on a table has nonzero gravity and normal force that cancel each other.' },
      { type: 'tf', q: 'Doubling the net force on an object while keeping its mass constant doubles its acceleration.',
        a: 'True. \\(a = F/m\\), so acceleration is directly proportional to net force when mass is constant.' },
      { type: 'tf', q: 'Internal forces within a system can change the total momentum of the system.',
        a: 'False. Internal forces come in action–reaction pairs that cancel. Only external forces change a system\'s total momentum.' },
      { type: 'tf', q: 'A person in an elevator accelerating upward feels heavier because the normal force exceeds their weight.',
        a: 'True. Newton\'s 2nd law gives \\(N - mg = ma\\), so \\(N = m(g+a) > mg\\). The scale reads more than actual weight.' },
      { type: 'tf', q: 'Net force equals mass times velocity.',
        a: 'False. \\(\\sum \\vec{F} = m\\vec{a}\\) — net force equals mass times acceleration, not velocity.' },
      { type: 'tf', q: 'Newton\'s 3rd law applies regardless of the masses of the two objects involved.',
        a: 'True. The law is absolute: \\(\\vec{F}_{A \\to B} = -\\vec{F}_{B \\to A}\\) for any pair, whether a planet and a pebble or two equal masses.' },
    ]
  },
  'forces': {
    title: 'Forces',
    back: '../forces/',
    cards: [
      { q: "Newton's law of universal gravitation",         a: '\\[\\left|\\vec{F}_g\\right| = G\\dfrac{m_1 m_2}{r^2}\\]',
        desc: '\\(G\\) = gravitational constant &nbsp;·&nbsp; \\(m_1,m_2\\) = masses &nbsp;·&nbsp; \\(r\\) = center-to-center distance<br><br><strong>In words:</strong> every pair of masses attracts, with stronger gravity for larger masses and weaker gravity at greater separation.' },
      { q: 'Gravitational field',                           a: '\\[\\vec{g} = -G\\dfrac{M}{r^2}\\hat{r}\\]',
        desc: '\\(M\\) = source mass &nbsp;·&nbsp; \\(r\\) = distance &nbsp;·&nbsp; \\(\\hat{r}\\) = outward unit vector<br><br><strong>In words:</strong> a mass creates an inward gravitational acceleration throughout the space around it.' },
      { q: "Weight near Earth's surface",                   a: '\\[F_g = mg \\quad (g \\approx 9.8\\,\\text{m/s}^2)\\]',
        desc: '\\(m\\) = mass &nbsp;·&nbsp; \\(g\\) = local gravitational field strength<br><br><strong>In words:</strong> weight is the gravitational force acting on an object near a planet surface.' },
      { q: 'Gravity components on an incline',              a: '\\[F_{g\\,\\parallel} = mg\\sin\\theta \\qquad F_{g\\,\\perp} = mg\\cos\\theta\\]',
        desc: '\\(m\\) = mass &nbsp;·&nbsp; \\(g\\) = gravitational acceleration &nbsp;·&nbsp; \\(\\theta\\) = incline angle<br><br><strong>In words:</strong> gravity splits into one component pulling down the ramp and another pressing into it.' },
      { q: 'Acceleration on a frictionless incline',        a: '\\[a = g\\sin\\theta\\]',
        desc: '\\(a\\) = acceleration down the ramp &nbsp;·&nbsp; \\(g\\) = gravitational acceleration &nbsp;·&nbsp; \\(\\theta\\) = incline angle<br><br><strong>In words:</strong> on a frictionless ramp, only the downhill component of gravity accelerates the object.' },
      { q: 'Kinetic friction',                              a: '\\[F_{f,k} = \\mu_k F_n\\]',
        desc: '\\(F_{f,k}\\) = kinetic friction &nbsp;·&nbsp; \\(\\mu_k\\) = kinetic friction coefficient &nbsp;·&nbsp; \\(F_n\\) = normal force<br><br><strong>In words:</strong> sliding friction grows with both surface roughness and how strongly the surfaces press together.' },
      { q: 'Maximum static friction',                       a: '\\[F_{f,s} \\leq \\mu_s F_n\\]',
        desc: '\\(F_{f,s}\\) = static friction &nbsp;·&nbsp; \\(\\mu_s\\) = static friction coefficient &nbsp;·&nbsp; \\(F_n\\) = normal force<br><br><strong>In words:</strong> static friction supplies only the force needed to prevent slipping, up to a maximum value.' },
      { q: "Hooke's law",                                   a: '\\[\\vec{F}_s = -k\\,\\Delta\\vec{x}\\]',
        desc: '\\(\\vec{F}_s\\) = spring force &nbsp;·&nbsp; \\(k\\) = spring constant &nbsp;·&nbsp; \\(\\Delta\\vec{x}\\) = displacement from equilibrium<br><br><strong>In words:</strong> a spring pushes or pulls back toward equilibrium more strongly as it is displaced farther.' },
      { type: 'tf', q: 'The normal force on an inclined surface equals \\(mg\\).',
        a: 'False. On an incline at angle \\(\\theta\\), the normal force is \\(F_n = mg\\cos\\theta\\), which is less than \\(mg\\).' },
      { type: 'tf', q: 'Halving the distance between two masses quadruples the gravitational force between them.',
        a: 'True. \\(F_g \\propto 1/r^2\\), so halving \\(r\\) gives \\(1/(r/2)^2 = 4/r^2\\), multiplying the force by 4.' },
      { type: 'tf', q: 'Static friction always equals \\(\\mu_s F_n\\).',
        a: 'False. Static friction matches the applied force and can be anywhere from 0 up to the maximum \\(\\mu_s F_n\\).' },
      { type: 'tf', q: 'A spring with a larger constant \\(k\\) is harder to stretch.',
        a: 'True. A larger \\(k\\) means more force is required per unit of displacement: \\(F = k\\,\\Delta x\\).' },
      { q: 'Normal force on an incline',                      a: '\\[F_n = mg\\cos\\theta\\]',
        desc: '\\(F_n\\) = normal force &nbsp;·&nbsp; \\(m\\) = mass &nbsp;·&nbsp; \\(\\theta\\) = incline angle<br><br><strong>In words:</strong> the ramp supports only the component of weight perpendicular to its surface.' },
      { q: 'Acceleration down incline with friction',         a: '\\[a = g(\\sin\\theta - \\mu_k\\cos\\theta)\\]',
        desc: '\\(a\\) = downhill acceleration &nbsp;·&nbsp; \\(\\theta\\) = incline angle &nbsp;·&nbsp; \\(\\mu_k\\) = kinetic friction coefficient<br><br><strong>In words:</strong> downhill gravity speeds the object up while kinetic friction reduces that acceleration.' },
      { type: 'tf', q: 'The normal force on an object always equals its weight.',
        a: 'False. On an incline \\(F_n = mg\\cos\\theta < mg\\). On a horizontal non-accelerating surface it equals weight, but that is a special case.' },
      { type: 'tf', q: 'Kinetic friction depends on how fast the surfaces slide against each other.',
        a: 'False. In the standard model \\(F_{f,k} = \\mu_k F_n\\) is independent of sliding speed. The coefficient \\(\\mu_k\\) is treated as constant.' },
      { type: 'tf', q: 'The component of gravity parallel to an incline increases as the angle increases.',
        a: 'True. \\(F_{g\\parallel} = mg\\sin\\theta\\) increases with \\(\\theta\\) from 0 at \\(0°\\) to the full weight \\(mg\\) at \\(90°\\).' },
      { type: 'tf', q: 'Stretching a spring twice as far stores twice the elastic potential energy.',
        a: 'False. \\(U_s = \\tfrac{1}{2}k(\\Delta x)^2\\); doubling \\(\\Delta x\\) quadruples the stored energy.' },
      { type: 'tf', q: 'Gravitational field strength decreases as you move farther from Earth.',
        a: 'True. \\(g = GM/r^2\\) decreases with distance. At twice the radius, \\(g\\) is one-quarter as strong.' },
      { type: 'tf', q: 'The maximum static friction force is always greater than the kinetic friction force for the same surfaces.',
        a: 'True. Typically \\(\\mu_s > \\mu_k\\), so \\(\\mu_s F_n > \\mu_k F_n\\). It takes more force to start sliding than to keep sliding.' },
      { type: 'tf', q: 'Friction on an incline always acts down the slope.',
        a: 'False. Friction opposes relative motion or tendency of motion. If the object tends to slide down, friction acts up; if pushed up the slope, friction acts down.' },
    ]
  },
  'circular-motion': {
    title: 'Circular Motion',
    back: '../circular-motion/',
    cards: [
      { q: 'Centripetal acceleration',                      a: '\\[a_c = \\dfrac{v^2}{r}\\]',
        desc: '\\(a_c\\) = centripetal acceleration &nbsp;·&nbsp; \\(v\\) = speed &nbsp;·&nbsp; \\(r\\) = radius<br><br><strong>In words:</strong> moving in a circle requires an inward acceleration that grows with speed and tighter curvature.' },
      { q: 'Net centripetal force',                         a: '\\[\\textstyle\\sum F_{\\text{rad}} = \\dfrac{mv^2}{r}\\]',
        desc: '\\(F_c\\) = net inward force &nbsp;·&nbsp; \\(m\\) = mass &nbsp;·&nbsp; \\(v\\) = speed &nbsp;·&nbsp; \\(r\\) = radius<br><br><strong>In words:</strong> centripetal force is the net inward force that continually turns an object along a circular path.' },
      { q: 'Period of circular motion',                     a: '\\[T = \\dfrac{2\\pi r}{v}\\]',
        desc: '\\(T\\) = time for one revolution &nbsp;·&nbsp; \\(r\\) = radius &nbsp;·&nbsp; \\(v\\) = speed<br><br><strong>In words:</strong> the period equals the circumference of the path divided by the speed around it.' },
      { q: 'Frequency',                                     a: '\\[f = \\dfrac{1}{T}\\]',
        desc: '\\(f\\) = cycles per second (Hz) &nbsp;·&nbsp; \\(T\\) = seconds per cycle<br><br><strong>In words:</strong> frequency and period are reciprocals because one counts cycles per second and the other seconds per cycle.' },
      { q: 'Orbital speed',                                 a: '\\[v^2 = \\dfrac{GM}{r}\\]',
        desc: '\\(G\\) = gravitational constant &nbsp;·&nbsp; \\(M\\) = central mass &nbsp;·&nbsp; \\(r\\) = orbital radius<br><br><strong>In words:</strong> orbital speed is set by the central mass and orbital distance, not by the orbiting object\'s mass.' },
      { q: "Kepler's 3rd law",                              a: '\\[T^2 = \\dfrac{4\\pi^2}{GM}\\,r^3\\]',
        desc: '\\(T\\) = orbital period &nbsp;·&nbsp; \\(r\\) = orbital radius &nbsp;·&nbsp; \\(M\\) = central mass<br><br><strong>In words:</strong> objects in larger circular orbits take longer to complete each revolution.' },
      { type: 'tf', q: 'Centripetal force is a new fundamental force of nature, separate from gravity and tension.',
        a: 'False. "Centripetal force" is just the net inward component of forces already present (gravity, tension, normal force, etc.).' },
      { type: 'tf', q: 'An object in uniform circular motion has constant velocity.',
        a: 'False. Speed is constant, but the direction of velocity continuously changes, so velocity is not constant.' },
      { type: 'tf', q: 'If the orbital radius of a satellite doubles, its orbital period doubles.',
        a: 'False. By Kepler\'s 3rd law \\(T^2 \\propto r^3\\), so doubling \\(r\\) multiplies \\(T\\) by \\(2^{3/2} \\approx 2.83\\).' },
      { q: 'Centripetal acceleration in terms of period',     a: '\\[a_c = \\dfrac{4\\pi^2 r}{T^2}\\]',
        desc: '\\(a_c\\) = centripetal acceleration &nbsp;·&nbsp; \\(r\\) = radius &nbsp;·&nbsp; \\(T\\) = period<br><br><strong>In words:</strong> shorter periods require greater inward acceleration to complete each circle more quickly.' },
      { q: 'Minimum speed at top of a vertical loop',         a: '\\[v_{\\min} = \\sqrt{gr}\\]',
        desc: '\\(v_{\\min}\\) = minimum top speed &nbsp;·&nbsp; \\(g\\) = gravitational acceleration &nbsp;·&nbsp; \\(r\\) = loop radius<br><br><strong>In words:</strong> at the minimum speed, gravity alone bends the path enough to keep the object moving around the loop.' },
      { type: 'tf', q: 'A satellite in a stable circular orbit is constantly accelerating.',
        a: 'True. Gravity continuously deflects the satellite toward Earth. It "falls around" the planet — constant speed but changing direction means nonzero acceleration.' },
      { type: 'tf', q: 'Planets farther from the Sun have longer orbital periods.',
        a: 'True. Kepler\'s 3rd law: \\(T^2 \\propto r^3\\), so larger orbital radius gives a longer period.' },
      { type: 'tf', q: 'Doubling the radius of a circular path at constant speed doubles the centripetal acceleration.',
        a: 'False. \\(a_c = v^2/r\\); doubling \\(r\\) at constant \\(v\\) halves the centripetal acceleration.' },
      { type: 'tf', q: 'The orbital period of a satellite depends on its mass.',
        a: 'False. \\(T^2 = (4\\pi^2/GM)r^3\\) depends only on the central mass \\(M\\) and orbital radius \\(r\\), not the satellite\'s mass.' },
      { type: 'tf', q: 'A string is most likely to break at the bottom of a vertical circle, not the top.',
        a: 'True. At the bottom, tension must support the weight and provide centripetal force: \\(T = mv^2/r + mg\\). At the top, \\(T = mv^2/r - mg\\), which is smaller.' },
      { type: 'tf', q: 'Orbital speed increases as a satellite moves to a higher orbit.',
        a: 'False. \\(v = \\sqrt{GM/r}\\); larger \\(r\\) gives smaller \\(v\\). Higher orbits are slower.' },
      { type: 'tf', q: 'An object in uniform circular motion has constant speed but nonzero acceleration.',
        a: 'True. Speed is constant, but velocity direction continuously changes, so \\(\\vec{a} = \\Delta\\vec{v}/\\Delta t \\neq 0\\). Acceleration points toward the center.' },
    ]
  },
  'work-energy': {
    title: 'Work & Energy',
    back: '../work-energy/',
    cards: [
      { q: 'Kinetic energy',                                a: '\\[K = \\dfrac{1}{2}mv^2\\]',
        desc: '\\(K\\) = kinetic energy &nbsp;·&nbsp; \\(m\\) = mass &nbsp;·&nbsp; \\(v\\) = speed &nbsp;·&nbsp; units: J<br><br><strong>In words:</strong> kinetic energy is energy of motion and grows with the square of speed.' },
      { q: 'Work-energy theorem',                           a: '\\[W_{\\text{net}} = \\Delta K\\]',
        desc: '\\(W_{\\text{net}}\\) = net work &nbsp;·&nbsp; \\(\\Delta K\\) = change in kinetic energy<br><br><strong>In words:</strong> positive net work speeds an object up, while negative net work slows it down.' },
      { q: 'Gravitational potential energy change',         a: '\\[\\Delta U_g = mg\\Delta y\\]',
        desc: '\\(\\Delta U_g\\) = gravitational potential energy change &nbsp;·&nbsp; \\(m\\) = mass &nbsp;·&nbsp; \\(\\Delta y\\) = height change<br><br><strong>In words:</strong> lifting an object stores gravitational energy, while lowering it releases that energy.' },
      { q: 'Spring potential energy',                       a: '\\[U_s = \\dfrac{1}{2}k(\\Delta x)^2\\]',
        desc: '\\(U_s\\) = spring potential energy &nbsp;·&nbsp; \\(k\\) = spring constant &nbsp;·&nbsp; \\(\\Delta x\\) = stretch or compression<br><br><strong>In words:</strong> deforming a spring stores energy, and doubling the deformation stores four times as much.' },
      { q: 'Mechanical energy',                             a: '\\[E_{\\text{mech}} = K + U\\]',
        desc: '\\(E_{\\text{mech}}\\) = mechanical energy &nbsp;·&nbsp; \\(K\\) = kinetic energy &nbsp;·&nbsp; \\(U\\) = potential energy<br><br><strong>In words:</strong> mechanical energy tracks the total energy associated with motion and position.' },
      { q: 'Conservation of energy (no external work or friction)',
                                                            a: '\\[\\Delta E_{\\text{mech}} = 0\\]',
        desc: '\\(K\\) = kinetic energy &nbsp;·&nbsp; \\(U\\) = potential energy &nbsp;·&nbsp; subscripts mark initial and final states<br><br><strong>In words:</strong> when only conservative forces act, energy shifts between motion and position without changing the total.' },
      { q: 'Energy with friction or external work',         a: '\\[W_{\\text{ext}} = \\Delta E_{\\text{mech}} + \\Delta E_{\\text{th}}\\]',
        desc: '\\(W_\\text{ext}\\) = external work &nbsp;·&nbsp; \\(\\Delta E_\\text{th}\\) = thermal energy change<br><br><strong>In words:</strong> external work adds or removes energy, while friction transfers mechanical energy into thermal energy.' },
      { type: 'tf', q: 'A force perpendicular to an object\'s motion does zero work on it.',
        a: 'True. Work \\(= F\\,d\\cos\\theta\\). When \\(\\theta = 90°\\), \\(\\cos 90° = 0\\), so work is zero.' },
      { type: 'tf', q: 'If the net work done on an object is zero, the object must be at rest.',
        a: 'False. Zero net work means zero change in kinetic energy. The object can still be moving at constant speed.' },
      { type: 'tf', q: 'Potential energy can be negative.',
        a: 'True. PE depends on the chosen reference point. Gravitational PE \\(\\Delta U = mg\\Delta y\\) is negative below the reference, and the exact formula \\(U_g = -Gm_1m_2/r\\) is always negative.' },
      { q: 'Work done by a constant force',                   a: '\\[W = Fd\\cos\\theta\\]',
        desc: '\\(W\\) = work &nbsp;·&nbsp; \\(F\\) = force magnitude &nbsp;·&nbsp; \\(d\\) = displacement &nbsp;·&nbsp; \\(\\theta\\) = angle between force and displacement<br><br><strong>In words:</strong> only the component of force parallel to the displacement transfers energy through work.' },
      { q: 'Nonconservative work theorem',                    a: '\\[W_{\\text{nc}} = \\Delta E_{\\text{mech}}\\]',
        desc: '\\(W_\\text{nc}\\) = nonconservative work &nbsp;·&nbsp; \\(\\Delta E_\\text{mech}\\) = mechanical energy change<br><br><strong>In words:</strong> friction and applied forces change the amount of mechanical energy in a system.' },
      { type: 'tf', q: 'The work done by gravity depends only on height change, not on the path taken.',
        a: 'True. Gravity is a conservative force. Work = \\(-mg\\Delta y\\), which depends only on vertical displacement.' },
      { type: 'tf', q: 'Doubling an object\'s kinetic energy doubles its speed.',
        a: 'False. \\(K = \\frac{1}{2}mv^2\\), so \\(v = \\sqrt{2K/m}\\). Doubling \\(K\\) multiplies speed by \\(\\sqrt{2} \\approx 1.41\\).' },
      { type: 'tf', q: 'A force applied perpendicular to an object\'s velocity can do no work.',
        a: 'True. Work \\(= \\vec{F}\\cdot\\vec{d} = Fd\\cos\\theta\\). At \\(\\theta = 90°\\), \\(W = 0\\). Normal force and centripetal force are examples.' },
      { type: 'tf', q: 'The work-energy theorem applies even when non-conservative forces act.',
        a: 'True. \\(W_{\\text{net}} = \\Delta K\\) always holds — it accounts for all forces, conservative or not.' },
      { type: 'tf', q: 'Friction violates conservation of energy.',
        a: 'False. Friction converts mechanical energy to thermal energy. Total energy is conserved; only mechanical energy decreases.' },
      { type: 'tf', q: 'A spring compressed by 2 cm stores four times the potential energy of one compressed by 1 cm.',
        a: 'True. \\(U_s = \\frac{1}{2}k(\\Delta x)^2\\). Doubling \\(\\Delta x\\) quadruples \\(U_s\\).' },
      { type: 'tf', q: 'Work done on an object can be negative.',
        a: 'True. If the force component along the displacement is opposite to the motion, \\(\\cos\\theta < 0\\) and work is negative (e.g., friction, drag).' },
      { q: 'Average power',                                   a: '\\[P_{\\text{avg}} = \\dfrac{W}{\\Delta t}\\]',
        desc: '\\(P_\\text{avg}\\) = average power &nbsp;·&nbsp; \\(W\\) = work done &nbsp;·&nbsp; \\(\\Delta t\\) = time interval &nbsp;·&nbsp; units: W<br><br><strong>In words:</strong> power measures how quickly work is done or energy is transferred.' },
      { q: 'Instantaneous power from force and velocity',     a: '\\[P = Fv\\cos\\theta\\]',
        desc: '\\(P\\) = instantaneous power &nbsp;·&nbsp; \\(F\\) = force magnitude &nbsp;·&nbsp; \\(v\\) = speed &nbsp;·&nbsp; \\(\\theta\\) = angle between force and velocity<br><br><strong>In words:</strong> a force transfers energy fastest when it points along the motion and does no instantaneous work when perpendicular.' },
      { type: 'tf', q: 'A watt is equivalent to one joule per second.',
        a: 'True. By definition, \\(1\\,\\text{W} = 1\\,\\text{J/s}\\). Power measures the rate of energy transfer.' },
      { type: 'tf', q: 'A force perpendicular to an object\'s velocity delivers zero power.',
        a: 'True. \\(P = Fv\\cos\\theta\\). At \\(\\theta = 90°\\), \\(P = 0\\). Normal force and centripetal force do no work and deliver no power.' },
      { type: 'tf', q: 'Doubling the speed of an object doubles the power delivered by a constant parallel force.',
        a: 'True. \\(P = Fv\\), so doubling \\(v\\) at constant \\(F\\) doubles \\(P\\).' },
      { type: 'tf', q: 'Two machines that do the same total work always have the same power.',
        a: 'False. Power depends on how quickly the work is done: \\(P = W/\\Delta t\\). The same work done in half the time requires twice the power.' },
    ]
  },
  'momentum': {
    title: 'Impulse & Momentum',
    back: '../momentum/',
    cards: [
      { q: 'Linear momentum',                               a: '\\[\\vec{p} = m\\vec{v}\\]',
        desc: '\\(\\vec{p}\\) = momentum &nbsp;·&nbsp; \\(m\\) = mass &nbsp;·&nbsp; \\(\\vec{v}\\) = velocity &nbsp;·&nbsp; units: kg·m/s<br><br><strong>In words:</strong> momentum measures translational motion and combines how much matter is moving with how fast and in what direction.' },
      { q: "Newton's 2nd law (momentum form)",              a: '\\[\\vec{F}_{\\text{net}} = \\dfrac{\\Delta \\vec{p}}{\\Delta t}\\]',
        desc: '\\(\\sum\\vec{F}\\) = net force &nbsp;·&nbsp; \\(d\\vec{p}/dt\\) = momentum change per unit time<br><br><strong>In words:</strong> a net force changes momentum, and a larger force changes it more quickly.' },
      { q: 'Impulse',                                       a: '\\[\\vec{J} = \\vec{F}\\,\\Delta t\\]',
        desc: '\\(\\vec{J}\\) = impulse &nbsp;·&nbsp; \\(\\vec{F}\\) = average force &nbsp;·&nbsp; \\(\\Delta t\\) = contact time &nbsp;·&nbsp; units: N·s<br><br><strong>In words:</strong> impulse measures the effect of a force acting over time and equals the area under a force-time graph.' },
      { q: 'Impulse-momentum theorem',                      a: '\\[\\vec{J}_{\\text{net}} = \\Delta \\vec{p} = m\\vec{v}_f - m\\vec{v}_i\\]',
        desc: '\\(\\vec{J}\\) = impulse &nbsp;·&nbsp; \\(\\Delta\\vec{p}\\) = final momentum minus initial momentum<br><br><strong>In words:</strong> every impulse changes an object\'s momentum by the same amount and in the same direction.' },
      { q: 'Conservation of momentum',                      a: '\\[\\textstyle\\sum \\vec{p}_i = \\sum \\vec{p}_f\\]',
        desc: '\\(\\vec{p}_{\\text{tot},i}\\) = initial total momentum &nbsp;·&nbsp; \\(\\vec{p}_{\\text{tot},f}\\) = final total momentum<br><br><strong>In words:</strong> without net external force, momentum can move between objects but the system total remains unchanged.' },
      { q: 'Two-body momentum conservation',                a: '\\[m_1\\vec{v}_{1i} + m_2\\vec{v}_{2i} = m_1\\vec{v}_{1f} + m_2\\vec{v}_{2f}\\]',
        desc: '\\(m_1,m_2\\) = masses &nbsp;·&nbsp; \\(v_{1i},v_{2i}\\) = initial velocities &nbsp;·&nbsp; \\(v_{1f},v_{2f}\\) = final velocities<br><br><strong>In words:</strong> during an isolated interaction, momentum lost by one object is gained by the other.' },
      { q: 'Center of mass velocity',                       a: '\\[\\vec{v}_{\\text{cm}} = \\dfrac{\\vec{p}_{\\text{tot}}}{M}\\]',
        desc: '\\(\\vec{v}_{\\text{cm}}\\) = center-of-mass velocity &nbsp;·&nbsp; \\(\\vec{p}_{\\text{tot}}\\) = total momentum &nbsp;·&nbsp; \\(M\\) = total mass<br><br><strong>In words:</strong> the whole system moves as if all its mass were concentrated at the center of mass.' },
      { q: 'Kinetic energy from momentum',                  a: '\\[K = \\dfrac{p^2}{2m}\\]',
        desc: '\\(K\\) = kinetic energy &nbsp;·&nbsp; \\(p\\) = momentum magnitude &nbsp;·&nbsp; \\(m\\) = mass<br><br><strong>In words:</strong> for the same momentum, a lighter object must move faster and therefore has more kinetic energy.' },
      { type: 'tf', q: 'A truck and a bicycle with the same momentum have the same kinetic energy.',
        a: 'False. \\(K = p^2/2m\\), so for equal momentum the lighter object has more kinetic energy.' },
      { type: 'tf', q: 'Increasing the contact time of a collision reduces the average force for the same momentum change.',
        a: 'True. \\(F_{\\text{avg}} = \\Delta p / \\Delta t\\). This is why airbags and crumple zones work.' },
      { type: 'tf', q: 'Impulse and momentum have the same units.',
        a: 'True. \\(1\\,\\text{N·s} = 1\\,\\text{kg·m/s}\\), consistent with \\(\\vec{J} = \\Delta \\vec{p}\\).' },
      { type: 'tf', q: "An object's momentum can change even if its speed stays constant.",
        a: 'True. Momentum is a vector. In uniform circular motion the speed is constant but the direction, and therefore \\(\\vec{p}\\), continuously changes.' },
      { type: 'tf', q: "Internal forces can change a system's total momentum.",
        a: 'False. Internal forces come in action-reaction pairs whose impulses cancel. Only a net external force changes total momentum.' },
      { type: 'tf', q: 'Two objects that explode apart from rest have equal and opposite momenta.',
        a: 'True. Total momentum starts at zero and must stay zero, so \\(\\vec{p}_1 = -\\vec{p}_2\\).' },
      { type: 'tf', q: 'The center of mass of a system can be accelerated by internal forces.',
        a: 'False. \\(\\vec{F}_{\\text{ext,net}} = M\\vec{a}_{\\text{cm}}\\). Internal forces cancel in pairs and never move the center of mass.' },
      { type: 'tf', q: 'Momentum is a scalar quantity.',
        a: 'False. Momentum is a vector, \\(\\vec{p} = m\\vec{v}\\), with direction along the velocity. Components are conserved independently.' },
    ]
  },
  'collisions': {
    title: 'Collisions',
    back: '../collisions/',
    cards: [
      { q: 'Perfectly inelastic collision',       a: '\\[\\vec{v}_f = \\dfrac{m_1\\vec{v}_{1i} + m_2\\vec{v}_{2i}}{m_1 + m_2}\\]',
        desc: '\\(m_1,m_2\\) = masses &nbsp;·&nbsp; \\(v_{1i},v_{2i}\\) = initial velocities &nbsp;·&nbsp; \\(v_f\\) = shared final velocity<br><br><strong>In words:</strong> when objects stick together, momentum is conserved but as much kinetic energy as possible becomes other forms.' },
      { q: 'Elastic 1D collision (target at rest)', a: '\\[v_{1f} = \\dfrac{m_1 - m_2}{m_1 + m_2}v_{1i} \\qquad v_{2f} = \\dfrac{2m_1}{m_1 + m_2}v_{1i}\\]',
        desc: '\\(m_1,m_2\\) = masses &nbsp;·&nbsp; \\(v_{1i}\\) = incoming speed &nbsp;·&nbsp; \\(v_{1f},v_{2f}\\) = final velocities<br><br><strong>In words:</strong> an elastic collision redistributes motion while preserving both total momentum and total kinetic energy.' },
      { q: 'Lorentz factor',                      a: '\\[\\gamma = \\dfrac{1}{\\sqrt{1 - v^2/c^2}}\\]',
        desc: '\\(\\gamma\\) = Lorentz factor &nbsp;·&nbsp; \\(v\\) = particle speed &nbsp;·&nbsp; \\(c\\) = speed of light<br><br><strong>In words:</strong> the Lorentz factor measures how strongly relativistic effects appear as speed approaches the speed of light.' },
      { q: 'Relativistic momentum',               a: '\\[\\vec{p} = \\gamma m\\vec{v}\\]',
        desc: '\\(\\vec{p}\\) = relativistic momentum &nbsp;·&nbsp; \\(\\gamma\\) = Lorentz factor &nbsp;·&nbsp; \\(m\\) = rest mass &nbsp;·&nbsp; \\(\\vec{v}\\) = velocity<br><br><strong>In words:</strong> momentum grows faster than \\(mv\\) at high speeds, making further acceleration increasingly difficult.' },
      { q: 'Relativistic energy',                 a: '\\[E^2 = p^2c^2 + m^2c^4\\]',
        desc: '\\(E\\) = total energy &nbsp;·&nbsp; \\(p\\) = momentum &nbsp;·&nbsp; \\(m\\) = rest mass &nbsp;·&nbsp; \\(c\\) = speed of light<br><br><strong>In words:</strong> total relativistic energy includes contributions from both rest mass and motion.' },
      { q: 'Mass energy (particle at rest)',      a: '\\[E = mc^2\\]',
        desc: '\\(E_0\\) = rest energy &nbsp;·&nbsp; \\(m\\) = rest mass &nbsp;·&nbsp; \\(c\\) = speed of light<br><br><strong>In words:</strong> mass itself stores energy even when an object is not moving.' },
      { q: 'Massless particle (photon)',          a: '\\[E = pc \\implies p = E/c\\]',
        desc: '\\(E\\) = photon energy &nbsp;·&nbsp; \\(p\\) = photon momentum &nbsp;·&nbsp; \\(c\\) = speed of light<br><br><strong>In words:</strong> light carries momentum in direct proportion to its energy even though photons have no rest mass.' },
      { type: 'tf', q: 'Momentum is conserved in every type of collision, as long as no net external force acts.',
        a: 'True. Elastic, inelastic, and perfectly inelastic collisions all conserve total momentum. Only kinetic energy distinguishes them.' },
      { type: 'tf', q: 'Kinetic energy is conserved in all collisions.',
        a: 'False. Only elastic collisions conserve kinetic energy. Inelastic collisions convert some of it to heat, sound, and deformation.' },
      { type: 'tf', q: 'In an elastic collision between equal masses where one is at rest, the objects exchange velocities.',
        a: 'True. With \\(m_1 = m_2\\), the formulas give \\(v_{1f} = 0\\) and \\(v_{2f} = v_{1i}\\), like billiard balls.' },
      { type: 'tf', q: 'If two colliding objects separate more slowly than they approached, the collision was inelastic.',
        a: 'True. Elastic collisions preserve relative speed: \\(v_{1i} - v_{2i} = -(v_{1f} - v_{2f})\\). A slower separation means kinetic energy was lost.' },
      { type: 'tf', q: 'Momentum is conserved in high-energy particle collisions, in each dimension separately.',
        a: 'True. Physicists use this to detect "missing" momentum, which reveals undetected particles such as neutrinos.' },
      { type: 'tf', q: 'Mass is conserved in particle collisions.',
        a: 'False. Only total relativistic energy is conserved. Energy of motion can convert into the rest mass of new particles, which is why the LHC needs near-light speeds.' },
      { type: 'tf', q: 'Photons carry no momentum because they have no mass.',
        a: 'False. For massless particles \\(E = pc\\), so \\(p = E/c\\). Photons participate in both energy and momentum conservation.' },
    ]
  },
  'rotational-kinematics': {
    title: 'Rotational Kinematics',
    back: '../rotational-kinematics/',
    cards: [
      { q: 'Average angular velocity',            a: '\\[\\omega_{\\text{avg}} = \\dfrac{\\Delta\\theta}{\\Delta t}\\]',
        desc: '\\(\\omega_{\\text{avg}}\\) = average angular velocity &nbsp;·&nbsp; \\(\\Delta\\theta\\) = angular displacement &nbsp;·&nbsp; \\(\\Delta t\\) = elapsed time<br><br><strong>In words:</strong> average angular velocity tells how quickly and in which direction an angle changes.' },
      { q: 'Average angular acceleration',        a: '\\[\\alpha_{\\text{avg}} = \\dfrac{\\Delta\\omega}{\\Delta t}\\]',
        desc: '\\(\\alpha_{\\text{avg}}\\) = average angular acceleration &nbsp;·&nbsp; \\(\\Delta\\omega\\) = angular velocity change &nbsp;·&nbsp; \\(\\Delta t\\) = elapsed time<br><br><strong>In words:</strong> average angular acceleration tells how quickly the spin rate or spin direction changes.' },
      { q: 'Radian measure of an angle',          a: '\\[\\theta = \\dfrac{s}{r}\\]',
        desc: '\\(\\theta\\) = angle in radians &nbsp;·&nbsp; \\(s\\) = arc length &nbsp;·&nbsp; \\(r\\) = distance from the axis<br><br><strong>In words:</strong> a radian measures angle by comparing the swept arc length with the circle radius.' },
      { q: 'Revolutions to radians',              a: '\\[1\\ \\text{rev} = 360^\\circ = 2\\pi\\ \\text{rad}\\]',
        desc: '\\(N\\) = number of revolutions &nbsp;·&nbsp; \\(\\Delta\\theta\\) = angular displacement in radians<br><br><strong>In words:</strong> each complete revolution adds \\(2\\pi\\) radians of angular displacement.' },
      { q: 'Arc length from rotation',            a: '\\[\\Delta s = r\\,\\Delta\\theta\\]',
        desc: '\\(s\\) = arc length &nbsp;·&nbsp; \\(r\\) = distance from the axis &nbsp;·&nbsp; \\(\\Delta\\theta\\) = angular displacement in radians<br><br><strong>In words:</strong> the same angle sweeps a longer path for points farther from the axis.' },
      { q: 'Linear speed of a rotating point',    a: '\\[v = r\\omega\\]',
        desc: '\\(v\\) = tangential speed &nbsp;·&nbsp; \\(r\\) = distance from the axis &nbsp;·&nbsp; \\(\\omega\\) = angular velocity<br><br><strong>In words:</strong> all points share the same angular velocity, but points farther out move faster along the circular path.' },
      { q: 'Tangential acceleration',             a: '\\[a_{\\text{tan}} = r\\alpha\\]',
        desc: '\\(a_t\\) = tangential acceleration &nbsp;·&nbsp; \\(r\\) = distance from the axis &nbsp;·&nbsp; \\(\\alpha\\) = angular acceleration<br><br><strong>In words:</strong> angular acceleration changes the tangential speed more strongly for points farther from the axis.' },
      { q: 'Rotational kinematic eq.: missing \\(\\theta\\)', a: '\\[\\omega = \\omega_0 + \\alpha t\\]',
        desc: '\\(\\omega\\) = final angular velocity &nbsp;·&nbsp; \\(\\omega_0\\) = initial angular velocity &nbsp;·&nbsp; \\(\\alpha\\) = constant angular acceleration<br><br><strong>In words:</strong> final spin rate equals the starting spin rate plus the change produced by angular acceleration over time.' },
      { q: 'Rotational kinematic eq.: missing \\(\\omega\\)', a: '\\[\\Delta\\theta = \\omega_0 t + \\tfrac{1}{2}\\alpha t^2\\]',
        desc: '\\(\\theta_0\\) = initial angle &nbsp;·&nbsp; \\(\\omega_0\\) = initial angular velocity &nbsp;·&nbsp; \\(\\alpha\\) = constant angular acceleration<br><br><strong>In words:</strong> angular position combines the starting angle, steady initial rotation, and extra rotation caused by angular acceleration.' },
      { q: 'Rotational kinematic eq.: missing \\(t\\)',       a: '\\[\\omega^2 = \\omega_0^2 + 2\\alpha\\,\\Delta\\theta\\]',
        desc: '\\(\\omega\\) = final angular velocity &nbsp;·&nbsp; \\(\\omega_0\\) = initial angular velocity &nbsp;·&nbsp; \\(\\alpha\\) = angular acceleration &nbsp;·&nbsp; \\(\\Delta\\theta\\) = angular displacement<br><br><strong>In words:</strong> this connects spin rate and angular displacement under constant angular acceleration without needing time.' },
      { type: 'tf', q: 'Every point on a rotating rigid body has the same angular velocity.',
        a: 'True. A rigid body holds its shape, so all points sweep the same angle in the same time. Otherwise the body would stretch or bunch up.' },
      { type: 'tf', q: 'Points farther from the axis of rotation have greater linear speed.',
        a: 'True. \\(v = r\\omega\\): the angular velocity is shared, so linear speed grows in proportion to \\(r\\).' },
      { type: 'tf', q: 'All points on a rotating rigid body travel the same distance in the same time.',
        a: 'False. They sweep the same angle, but distance is \\(\\Delta s = r\\Delta\\theta\\), so points farther from the axis travel farther.' },
      { type: 'tf', q: 'A body spinning at constant angular velocity has zero angular acceleration, but its points still accelerate.',
        a: 'True. \\(\\alpha = 0\\) when \\(\\omega\\) is constant, yet each point has centripetal acceleration \\(a_c = v^2/r\\) from its changing direction.' },
      { type: 'tf', q: 'The radian is a dimensionless unit.',
        a: 'True. \\(\\theta = s/r\\) is a ratio of two lengths, which is why \\(v = r\\omega\\) yields plain m/s.' },
      { type: 'tf', q: 'The relation \\(a_{\\text{tan}} = r\\alpha\\) accounts for the centripetal acceleration of a rotating point.',
        a: 'False. It gives only the tangential component, from the changing spin rate. Centripetal acceleration \\(v^2/r\\) exists even when \\(\\alpha = 0\\).' },
      { type: 'tf', q: 'By convention, counterclockwise rotation is taken as positive.',
        a: 'True. Counterclockwise angular quantities are positive and clockwise ones negative, mirroring the sign conventions of linear kinematics.' },
      { type: 'tf', q: 'A negative angular acceleration always means the object is slowing down.',
        a: 'False. If \\(\\omega\\) is also negative (clockwise), a negative \\(\\alpha\\) speeds the rotation up. Slowing requires \\(\\alpha\\) opposite in sign to \\(\\omega\\).' },
    ]
  },
  'rotational-dynamics': {
    title: 'Torque & Rotational Dynamics',
    back: '../rotational-dynamics/',
    cards: [
      { q: 'Torque',                              a: '\\[\\tau = rF\\sin\\theta\\]',
        desc: '\\(\\tau\\) = torque &nbsp;·&nbsp; \\(r\\) = distance from the axis &nbsp;·&nbsp; \\(F\\) = applied force &nbsp;·&nbsp; \\(\\theta\\) = angle between \\(\\vec{r}\\) and \\(\\vec{F}\\) &nbsp;·&nbsp; units: N·m<br><br><strong>In words:</strong> torque measures how effectively a force twists an object about an axis.' },
      { q: 'Lever arm',                           a: '\\[r_\\perp = r\\sin\\theta\\]',
        desc: '\\(r_\\perp\\) = lever arm &nbsp;·&nbsp; \\(r\\) = distance to where the force acts &nbsp;·&nbsp; \\(\\theta\\) = force angle &nbsp;·&nbsp; units: m<br><br><strong>In words:</strong> the lever arm is the perpendicular distance that determines how much of a force produces rotation.' },
      { q: 'Torque sign convention',              a: '\\[\\text{ccw } (+) \\quad \\text{cw } (-)\\]',
        desc: 'ccw = counterclockwise &nbsp;·&nbsp; cw = clockwise<br><br><strong>In words:</strong> the sign of torque identifies which direction the force tends to rotate the object.' },
      { q: 'Rotational inertia (definition)',     a: '\\[I = \\sum m r^2\\]',
        desc: '\\(I\\) = rotational inertia &nbsp;·&nbsp; \\(m\\) = each piece of mass &nbsp;·&nbsp; \\(r\\) = its distance from the axis &nbsp;·&nbsp; units: kg·m²<br><br><strong>In words:</strong> rotational inertia measures how strongly a system resists a change in its rotation, with distant mass counting more.' },
      { q: 'Rotational inertia: hoop or point mass', a: '\\[I = MR^2\\]',
        desc: '\\(I\\) = rotational inertia &nbsp;·&nbsp; \\(M\\) = total mass &nbsp;·&nbsp; \\(R\\) = distance from the axis &nbsp;·&nbsp; units: kg·m²<br><br><strong>In words:</strong> placing all the mass at the outer radius makes a hoop especially resistant to changes in rotation.' },
      { q: 'Rotational inertia: solid disk',      a: '\\[I = \\tfrac{1}{2}MR^2\\]',
        desc: '\\(I\\) = rotational inertia &nbsp;·&nbsp; \\(M\\) = disk mass &nbsp;·&nbsp; \\(R\\) = disk radius &nbsp;·&nbsp; units: kg·m²<br><br><strong>In words:</strong> a solid disk is easier to spin than a hoop of equal mass and radius because some of its mass lies closer to the axis.' },
      { q: 'Rotational inertia: solid sphere',    a: '\\[I = \\tfrac{2}{5}MR^2\\]',
        desc: '\\(I\\) = rotational inertia &nbsp;·&nbsp; \\(M\\) = sphere mass &nbsp;·&nbsp; \\(R\\) = sphere radius &nbsp;·&nbsp; units: kg·m²<br><br><strong>In words:</strong> a solid sphere has relatively low rotational inertia because much of its mass lies close to the axis.' },
      { q: 'Rotational inertia: thin rod',        a: '\\[I_\\text{center} = \\tfrac{1}{12}ML^2 \\quad I_\\text{end} = \\tfrac{1}{3}ML^2\\]',
        desc: '\\(I\\) = rotational inertia &nbsp;·&nbsp; \\(M\\) = rod mass &nbsp;·&nbsp; \\(L\\) = rod length &nbsp;·&nbsp; units: kg·m²<br><br><strong>In words:</strong> the same rod is four times harder to spin about its end than about its center.' },
      { q: 'Newton\'s second law, rotational form', a: '\\[\\tau_\\text{net} = I\\alpha\\]',
        desc: '\\(\\tau_\\text{net}\\) = net torque &nbsp;·&nbsp; \\(I\\) = rotational inertia &nbsp;·&nbsp; \\(\\alpha\\) = angular acceleration<br><br><strong>In words:</strong> net torque changes rotational motion, while rotational inertia determines how difficult that change is.' },
      { q: 'Rotational equilibrium',              a: '\\[\\tau_\\text{net} = 0 \\implies \\alpha = 0\\]',
        desc: '\\(\\tau_\\text{net}\\) = net torque &nbsp;·&nbsp; \\(\\alpha\\) = angular acceleration &nbsp;·&nbsp; \\(\\omega\\) = angular velocity<br><br><strong>In words:</strong> balanced torques cause no change in angular velocity, so the object stays at rest or keeps spinning steadily.' },
      { q: 'Angular momentum of a rigid system',  a: '\\[L = I\\omega\\]',
        desc: '\\(L\\) = angular momentum &nbsp;·&nbsp; \\(I\\) = rotational inertia about the chosen axis &nbsp;·&nbsp; \\(\\omega\\) = angular velocity &nbsp;·&nbsp; units: kg·m²/s<br><br><strong>In words:</strong> angular momentum measures how much rotational motion a rigid system has about a chosen axis.' },
      { q: 'Angular impulse-momentum theorem',     a: '\\[\\Delta\\vec{L} = \\sum\\vec{\\tau}\\,\\Delta t\\]',
        desc: '\\(\\Delta\\vec{L}\\) = change in angular momentum &nbsp;·&nbsp; \\(\\sum\\vec{\\tau}\\) = net torque &nbsp;·&nbsp; \\(\\Delta t\\) = time interval &nbsp;·&nbsp; units: kg·m²/s or N·m·s<br><br><strong>In words:</strong> applying a net torque over time delivers angular impulse and changes the system\'s angular momentum in the torque\'s direction.' },
      { type: 'tf', q: 'A force directed straight at the axis of rotation produces zero torque.',
        a: 'True. Its line of action passes through the axis, so the lever arm \\(r\\sin\\theta\\) is zero. Pushing a door toward its hinges never opens it.' },
      { type: 'tf', q: 'In an extended free-body diagram, gravity is drawn at the object\'s center of mass.',
        a: 'True. Unlike a point free-body diagram, force placement matters for torque, and gravity effectively acts at the center of mass.' },
      { type: 'tf', q: 'Forces acting at the pivot contribute torque about the pivot.',
        a: 'False. At the pivot \\(r = 0\\), so they exert no torque. Choosing the pivot as the axis removes those unknowns from the equation.' },
      { type: 'tf', q: 'Two objects with the same mass and radius always have the same rotational inertia.',
        a: 'False. \\(I\\) depends on how the mass is distributed: a hoop (\\(MR^2\\)) resists spinning more than a disk (\\(\\tfrac{1}{2}MR^2\\)) of equal mass and radius.' },
      { type: 'tf', q: 'A skater pulling their arms in decreases their rotational inertia.',
        a: 'True. Bringing mass closer to the axis shrinks each \\(mr^2\\) term, which is why the spin speeds up.' },
      { type: 'tf', q: 'If the net torque on an object is zero, the object cannot be rotating.',
        a: 'False. Zero net torque means zero angular acceleration. The object can keep spinning at constant \\(\\omega\\), just as zero net force allows constant velocity.' },
      { type: 'tf', q: 'Angular impulse points in the same direction as the torque that produces it.',
        a: 'True. \\(\\Delta\\vec{L} = \\sum\\vec{\\tau}\\,\\Delta t\\), so angular impulse, net torque, and the change in angular momentum align.' },
      { type: 'tf', q: 'Doubling the distance of a point mass from the axis doubles its rotational inertia.',
        a: 'False. \\(I = mr^2\\), so doubling \\(r\\) quadruples the rotational inertia.' },
      { type: 'tf', q: 'For a balanced seesaw, the lighter rider must sit farther from the pivot.',
        a: 'True. Balance requires equal and opposite torques: \\(m_1 g r_1 = m_2 g r_2\\), so less mass needs more distance.' },
    ]
  },
  'rotational-energy': {
    title: 'Rotational Energy',
    back: '../rotational-energy/',
    cards: [
      { q: 'Rotational kinetic energy',            a: '\\[K_\\text{rot} = \\tfrac{1}{2}I\\omega^2\\]',
        desc: '\\(K_\\text{rot}\\) = rotational kinetic energy &nbsp;·&nbsp; \\(I\\) = rotational inertia &nbsp;·&nbsp; \\(\\omega\\) = angular velocity &nbsp;·&nbsp; units: J<br><br><strong>In words:</strong> rotational kinetic energy is energy of spinning and grows with both rotational inertia and the square of angular speed.' },
      { q: 'Translational kinetic energy',         a: '\\[K_\\text{trans} = \\tfrac{1}{2}Mv_\\text{cm}^2\\]',
        desc: '\\(K_\\text{trans}\\) = translational kinetic energy &nbsp;·&nbsp; \\(M\\) = total mass &nbsp;·&nbsp; \\(v_\\text{cm}\\) = center-of-mass speed<br><br><strong>In words:</strong> translational kinetic energy describes the motion of the rigid system as a whole.' },
      { q: 'Total kinetic energy of a rigid system', a: '\\[K = \\tfrac{1}{2}Mv_\\text{cm}^2 + \\tfrac{1}{2}I_\\text{cm}\\omega^2\\]',
        desc: '\\(M\\) = total mass &nbsp;·&nbsp; \\(v_\\text{cm}\\) = center-of-mass speed &nbsp;·&nbsp; \\(I_\\text{cm}\\) = rotational inertia about the center of mass &nbsp;·&nbsp; \\(\\omega\\) = angular velocity<br><br><strong>In words:</strong> a moving rigid system can carry energy through both overall motion and spinning.' },
      { q: 'Rolling without slipping constraint',  a: '\\[v_\\text{cm} = R\\omega\\]',
        desc: '\\(v_\\text{cm}\\) = center-of-mass speed &nbsp;·&nbsp; \\(R\\) = radius &nbsp;·&nbsp; \\(\\omega\\) = angular velocity<br><br><strong>In words:</strong> rolling without slipping locks forward motion to rotation so the contact point is instantaneously at rest.' },
      { q: 'Total KE of a rolling solid disk',     a: '\\[K = \\tfrac{3}{4}Mv_\\text{cm}^2\\]',
        desc: '\\(K\\) = total kinetic energy &nbsp;·&nbsp; \\(M\\) = disk mass &nbsp;·&nbsp; \\(v_\\text{cm}\\) = center-of-mass speed<br><br><strong>In words:</strong> a rolling disk divides its kinetic energy between translation and rotation, with one third in rotation.' },
      { q: 'Energy conservation rolling down a ramp', a: '\\[Mgh = \\tfrac{1}{2}Mv_\\text{cm}^2 + \\tfrac{1}{2}I_\\text{cm}\\omega^2\\]',
        desc: '\\(h\\) = vertical drop &nbsp;·&nbsp; \\(v_\\text{cm}\\) = final center-of-mass speed &nbsp;·&nbsp; \\(I_\\text{cm}\\) = rotational inertia<br><br><strong>In words:</strong> gravitational potential energy becomes both forward-motion energy and spinning energy as an object rolls downhill.' },
      { q: 'Ramp-bottom speed for \\(I = cMR^2\\)', a: '\\[v_\\text{cm} = \\sqrt{\\dfrac{2gh}{1 + c}}\\]',
        desc: '\\(v_\\text{cm}\\) = bottom speed &nbsp;·&nbsp; \\(h\\) = vertical drop &nbsp;·&nbsp; \\(c\\) = shape factor in \\(I=cMR^2\\)<br><br><strong>In words:</strong> shapes with less rotational inertia reach the bottom faster because less energy is required for spinning.' },
      { q: 'Speed of the top of a rolling wheel',  a: '\\[v_\\text{top} = 2v_\\text{cm}\\]',
        desc: '\\(v_\\text{top}\\) = speed of the top point &nbsp;·&nbsp; \\(v_\\text{cm}\\) = center-of-mass speed<br><br><strong>In words:</strong> translation and rotation add at the top of a rolling wheel and cancel at the point touching the ground.' },
      { type: 'tf', q: 'Rotational kinetic energy is a scalar quantity.',
        a: 'True. \\(K_\\text{rot} = \\tfrac{1}{2}I\\omega^2\\) squares the angular velocity, so spin direction drops out and the result is never negative.' },
      { type: 'tf', q: 'Two identical wheels spinning at the same rate in opposite directions have zero total rotational kinetic energy.',
        a: 'False. Kinetic energies are scalars and always add: each wheel contributes a positive \\(\\tfrac{1}{2}I\\omega^2\\).' },
      { type: 'tf', q: 'A rolling object\'s total kinetic energy is its translational KE plus its rotational KE about the center of mass.',
        a: 'True. \\(K = \\tfrac{1}{2}Mv_\\text{cm}^2 + \\tfrac{1}{2}I_\\text{cm}\\omega^2\\): the split is exact for any rigid body.' },
      { type: 'tf', q: 'Static friction does no work on an object rolling without slipping.',
        a: 'True. It acts on the contact point, which is momentarily at rest, so mechanical energy is conserved.' },
      { type: 'tf', q: 'A ball rolling down a ramp arrives faster than an identical ball sliding down without friction.',
        a: 'False. The roller must spend part of \\(Mgh\\) on rotation, so it arrives slower: \\(\\sqrt{2gh/(1+c)}\\) versus \\(\\sqrt{2gh}\\).' },
      { type: 'tf', q: 'In a rolling race down a ramp, a heavier sphere beats a lighter one of the same shape.',
        a: 'False. Mass and radius cancel in \\(v = \\sqrt{2gh/(1+c)}\\); only the shape factor \\(c\\) matters, so identical shapes tie.' },
      { type: 'tf', q: 'A hoop reaches the bottom of a ramp after a solid sphere released at the same time.',
        a: 'True. The hoop\'s \\(c = 1\\) locks half its energy in rotation, while the sphere\'s \\(c = \\tfrac{2}{5}\\) keeps more in translation.' },
      { type: 'tf', q: 'Doubling an object\'s angular velocity doubles its rotational kinetic energy.',
        a: 'False. \\(K_\\text{rot} \\propto \\omega^2\\), so doubling \\(\\omega\\) quadruples the rotational kinetic energy.' },
      { type: 'tf', q: 'A skidding tire satisfies \\(v_\\text{cm} = R\\omega\\).',
        a: 'False. Slipping breaks the rolling constraint: a locked, skidding tire has \\(\\omega = 0\\) while \\(v_\\text{cm} \\neq 0\\), and kinetic friction dissipates energy.' },
    ]
  }
};
