window.FC_DECKS = {
  'kinematics': {
    title: 'Kinematics',
    back: '../kinematics/',
    cards: [
      { q: 'Average velocity',                              a: '\\[v = \\dfrac{\\Delta x}{\\Delta t}\\]',
        desc: '\\(\\Delta x\\) = displacement &nbsp;·&nbsp; \\(\\Delta t\\) = elapsed time' },
      { q: 'Average acceleration',                          a: '\\[a = \\dfrac{\\Delta v}{\\Delta t}\\]',
        desc: '\\(\\Delta v\\) = change in velocity &nbsp;·&nbsp; \\(\\Delta t\\) = elapsed time' },
      { q: 'Kinematic eq. &#x2014; missing \\(x\\)',        a: '\\[v = v_0 + at\\]',
        desc: '\\(v_0\\) = initial velocity &nbsp;·&nbsp; \\(a\\) = acceleration &nbsp;·&nbsp; \\(t\\) = time' },
      { q: 'Kinematic eq. &#x2014; missing \\(v\\)',        a: '\\[x = x_0 + v_0 t + \\tfrac{1}{2}at^2\\]',
        desc: '\\(x_0\\) = initial position &nbsp;·&nbsp; \\(v_0\\) = initial velocity' },
      { q: 'Kinematic eq. &#x2014; missing \\(t\\)',        a: '\\[v^2 = v_0^2 + 2a(x - x_0)\\]',
        desc: 'use when time is unknown' },
      { q: 'Kinematic eq. &#x2014; missing \\(a\\)',        a: '\\[x - x_0 = \\tfrac{1}{2}(v_0 + v)\\,t\\]',
        desc: 'average velocity \\(\\times\\) time; use when acceleration is unknown' },
      { q: 'Vector components',                             a: '\\[v_x = v\\cos\\theta \\qquad v_y = v\\sin\\theta\\]',
        desc: '\\(\\theta\\) = angle from the positive x-axis' },
      { q: 'Resultant magnitude and angle',                 a: '\\[v = \\sqrt{v_x^2 + v_y^2} \\qquad \\theta = \\tan^{-1}\\!\\left(\\dfrac{v_y}{v_x}\\right)\\]',
        desc: 'Pythagorean theorem for magnitude; \\(\\theta\\) is direction angle' },
      { q: 'Projectile motion: horizontal',                 a: '\\[v_x = v_{x0} \\qquad x = x_0 + v_{x0}\\,t\\]',
        desc: '\\(v_{x0}\\) = initial horizontal velocity; horizontal speed is constant' },
      { q: 'Projectile motion: vertical',                   a: '\\[v_y = v_{y0} - gt \\qquad y = y_0 + v_{y0}\\,t - \\tfrac{1}{2}gt^2\\]',
        desc: '\\(g \\approx 9.8\\) m/s² downward &nbsp;·&nbsp; \\(v_{y0}\\) = initial vertical velocity' },
      { type: 'tf', q: 'An object with zero acceleration must be at rest.',
        a: 'False. Zero acceleration means constant velocity, which can be any value including nonzero.' },
      { type: 'tf', q: 'The slope of a velocity-time graph gives acceleration.',
        a: 'True. \\(a = \\Delta v / \\Delta t\\) is the rise-over-run of the \\(v\\)-\\(t\\) graph.' },
      { type: 'tf', q: 'A projectile at its highest point has zero acceleration.',
        a: 'False. Vertical velocity is zero at the peak, but acceleration is still \\(g\\) downward throughout the flight.' },
      { type: 'tf', q: 'An object can have velocity and acceleration pointing in opposite directions.',
        a: 'True. This simply means the object is slowing down (e.g., a ball thrown upward on the way up).' },
      { q: 'Vertical kinematic eq. &#x2014; missing \\(t\\)',  a: '\\[v_y^2 = v_{y0}^2 - 2g\\,\\Delta y\\]',
        desc: '\\(v_{y0}\\) = initial vertical velocity &nbsp;·&nbsp; \\(\\Delta y\\) = vertical displacement; use when time is unknown' },
      { type: 'tf', q: 'The displacement of an object always equals the total distance it travels.',
        a: 'False. Distance is total path length (scalar); displacement is the net change in position (vector). They match only when motion is in one direction without backtracking.' },
      { type: 'tf', q: 'The area under a velocity–time graph equals the object\'s displacement.',
        a: 'True. By definition \\(\\Delta x = \\int v\\,dt\\), which is the area under the \\(v\\)-\\(t\\) curve.' },
      { type: 'tf', q: 'For a projectile launched horizontally, the time of flight depends on the launch speed.',
        a: 'False. Hang time depends only on vertical free fall: \\(h = \\tfrac{1}{2}gt^2\\). Horizontal speed affects range, not flight time.' },
      { type: 'tf', q: 'At the peak of a projectile\'s trajectory, only the vertical component of velocity is zero.',
        a: 'True. \\(v_y = 0\\) at the peak, but horizontal velocity \\(v_x = v_{x0}\\) remains unchanged throughout.' },
      { type: 'tf', q: 'The slope of a position–time graph at any point gives the instantaneous velocity at that moment.',
        a: 'True. Instantaneous velocity is the derivative of position with respect to time, which equals the tangent slope of the \\(x\\)-\\(t\\) graph.' },
      { type: 'tf', q: 'An object can have a constant speed while its velocity is changing.',
        a: 'True. Velocity is a vector; if direction changes (e.g., circular motion), velocity changes even when speed stays constant.' },
      { type: 'tf', q: 'In a vacuum, two objects of different masses dropped from the same height hit the ground at the same time.',
        a: 'True. Free-fall acceleration \\(g\\) is independent of mass, so both experience the same \\(g\\) and fall identically.' },
      { type: 'tf', q: 'If an object returns to its starting point, its displacement is zero but distance traveled may not be.',
        a: 'True. Displacement is the net vector from start to finish — zero for a round trip. Distance is total path length, which is nonzero.' },
    ]
  },
  'dynamics': {
    title: 'Dynamics',
    back: '../force-dynamics/',
    cards: [
      { q: "Newton's 1st law",                              a: '\\[\\textstyle\\sum \\vec{F} = 0 \\iff \\vec{a} = 0\\]',
        desc: 'zero net force means zero acceleration (constant or zero velocity)' },
      { q: "Newton's 2nd law",                              a: '\\[\\textstyle\\sum \\vec{F} = m\\vec{a}\\]',
        desc: '\\(m\\) = mass (kg) &nbsp;·&nbsp; \\(\\vec{a}\\) = acceleration (m/s²)' },
      { q: "Newton's 3rd law",                              a: '\\[\\vec{F}_{A \\to B} = -\\vec{F}_{B \\to A}\\]',
        desc: 'action-reaction pairs are equal in magnitude, opposite in direction, on different objects' },
      { q: 'Component form of the 2nd law',                 a: '\\[\\textstyle\\sum F_x = ma_x \\qquad \\sum F_y = ma_y\\]',
        desc: 'apply independently along each axis' },
      { q: 'Center of mass',                                a: '\\[x_{\\text{cm}} = \\dfrac{\\sum m_i\\, x_i}{\\sum m_i}\\]',
        desc: '\\(m_i\\) = mass of particle \\(i\\) &nbsp;·&nbsp; \\(x_i\\) = its position' },
      { type: 'tf', q: 'Two objects with the same net force always have the same acceleration.',
        a: 'False. Acceleration also depends on mass: \\(a = F/m\\). Same force on a heavier object gives less acceleration.' },
      { type: 'tf', q: 'An object moving at constant velocity has zero net force acting on it.',
        a: "True. Newton's 1st law: constant velocity (including constant zero) requires \\(\\sum \\vec{F} = 0\\)." },
      { type: 'tf', q: "Newton's 3rd law force pairs act on the same object.",
        a: 'False. They always act on two different objects: if A pulls B, B pulls A with equal force in the opposite direction.' },
      { q: 'Two-body center of mass',                         a: '\\[x_{\\text{cm}} = \\dfrac{m_1 x_1 + m_2 x_2}{m_1 + m_2}\\]',
        desc: '\\(m_1, m_2\\) = masses &nbsp;·&nbsp; \\(x_1, x_2\\) = positions; cm is always closer to the heavier mass' },
      { type: 'tf', q: 'The center of mass of two unequal masses lies at the geometric midpoint between them.',
        a: 'False. The center of mass is closer to the heavier mass. It is at the midpoint only when the masses are equal.' },
      { type: 'tf', q: 'An object in translational equilibrium must be at rest.',
        a: 'False. Equilibrium means zero net force, which means zero acceleration. An object moving at constant velocity is also in equilibrium.' },
      { type: 'tf', q: 'If the net force on an object is zero, every individual force acting on it must be zero.',
        a: 'False. Multiple nonzero forces can sum to zero net force. A book on a table has nonzero gravity and normal force that cancel each other.' },
      { type: 'tf', q: 'Doubling the net force on an object while keeping its mass constant doubles its acceleration.',
        a: 'True. \\(a = F/m\\), so acceleration is directly proportional to net force when mass is constant.' },
      { type: 'tf', q: 'Internal forces within a system can change the total momentum of the system.',
        a: 'False. Internal forces come in action–reaction pairs that cancel. Only external forces change a system\'s total momentum.' },
      { type: 'tf', q: 'A person in an elevator accelerating upward feels heavier because the normal force exceeds their weight.',
        a: 'True. Newton\'s 2nd law gives \\(N - mg = ma\\), so \\(N = m(g+a) > mg\\). The scale reads more than actual weight.' },
      { type: 'tf', q: 'Net force equals mass times velocity.',
        a: 'False. \\(\\sum \\vec{F} = m\\vec{a}\\) — net force equals mass times acceleration, not velocity.' },
      { type: 'tf', q: 'Newton\'s 3rd law applies regardless of the masses of the two objects involved.',
        a: 'True. The law is absolute: \\(\\vec{F}_{A \\to B} = -\\vec{F}_{B \\to A}\\) for any pair, whether a planet and a pebble or two equal masses.' },
    ]
  },
  'forces': {
    title: 'Forces',
    back: '../forces/',
    cards: [
      { q: "Newton's law of universal gravitation",         a: '\\[\\left|\\vec{F}_g\\right| = G\\dfrac{m_1 m_2}{r^2}\\]',
        desc: '\\(G = 6.674\\times10^{-11}\\) N m² kg⁻² &nbsp;·&nbsp; \\(r\\) = center-to-center distance' },
      { q: 'Gravitational field',                           a: '\\[\\vec{g} = -G\\dfrac{M}{r^2}\\hat{r}\\]',
        desc: '\\(M\\) = source mass &nbsp;·&nbsp; \\(r\\) = distance &nbsp;·&nbsp; \\(\\hat{r}\\) = outward unit vector' },
      { q: "Weight near Earth's surface",                   a: '\\[F_g = mg \\quad (g \\approx 9.8\\,\\text{m/s}^2)\\]',
        desc: '\\(m\\) = mass &nbsp;·&nbsp; valid only near Earth\'s surface where \\(g\\) is roughly constant' },
      { q: 'Gravity components on an incline',              a: '\\[F_{g\\,\\parallel} = mg\\sin\\theta \\qquad F_{g\\,\\perp} = mg\\cos\\theta\\]',
        desc: '\\(\\theta\\) = angle between incline and horizontal' },
      { q: 'Acceleration on a frictionless incline',        a: '\\[a = g\\sin\\theta\\]',
        desc: '\\(\\theta\\) = incline angle; follows from \\(F_{g\\parallel} = ma\\)' },
      { q: 'Kinetic friction',                              a: '\\[F_{f,k} = \\mu_k F_n\\]',
        desc: '\\(\\mu_k\\) = kinetic friction coefficient &nbsp;·&nbsp; \\(F_n\\) = normal force' },
      { q: 'Maximum static friction',                       a: '\\[F_{f,s} \\leq \\mu_s F_n\\]',
        desc: '\\(\\mu_s\\) = static friction coefficient; friction adjusts up to this maximum' },
      { q: "Hooke's law",                                   a: '\\[\\vec{F}_s = -k\\,\\Delta\\vec{x}\\]',
        desc: '\\(k\\) = spring constant (N/m) &nbsp;·&nbsp; \\(\\Delta x\\) = displacement from equilibrium' },
      { type: 'tf', q: 'The normal force on an inclined surface equals \\(mg\\).',
        a: 'False. On an incline at angle \\(\\theta\\), the normal force is \\(F_n = mg\\cos\\theta\\), which is less than \\(mg\\).' },
      { type: 'tf', q: 'Halving the distance between two masses quadruples the gravitational force between them.',
        a: 'True. \\(F_g \\propto 1/r^2\\), so halving \\(r\\) gives \\(1/(r/2)^2 = 4/r^2\\), multiplying the force by 4.' },
      { type: 'tf', q: 'Static friction always equals \\(\\mu_s F_n\\).',
        a: 'False. Static friction matches the applied force and can be anywhere from 0 up to the maximum \\(\\mu_s F_n\\).' },
      { type: 'tf', q: 'A spring with a larger constant \\(k\\) is harder to stretch.',
        a: 'True. A larger \\(k\\) means more force is required per unit of displacement: \\(F = k\\,\\Delta x\\).' },
      { q: 'Normal force on an incline',                      a: '\\[F_n = mg\\cos\\theta\\]',
        desc: '\\(\\theta\\) = incline angle &nbsp;·&nbsp; \\(F_n < mg\\) for any nonzero angle' },
      { q: 'Acceleration down incline with friction',         a: '\\[a = g(\\sin\\theta - \\mu_k\\cos\\theta)\\]',
        desc: '\\(\\theta\\) = incline angle &nbsp;·&nbsp; \\(\\mu_k\\) = kinetic friction coefficient' },
      { type: 'tf', q: 'The normal force on an object always equals its weight.',
        a: 'False. On an incline \\(F_n = mg\\cos\\theta < mg\\). On a horizontal non-accelerating surface it equals weight, but that is a special case.' },
      { type: 'tf', q: 'Kinetic friction depends on how fast the surfaces slide against each other.',
        a: 'False. In the standard model \\(F_{f,k} = \\mu_k F_n\\) is independent of sliding speed. The coefficient \\(\\mu_k\\) is treated as constant.' },
      { type: 'tf', q: 'The component of gravity parallel to an incline increases as the angle increases.',
        a: 'True. \\(F_{g\\parallel} = mg\\sin\\theta\\) increases with \\(\\theta\\) from 0 at \\(0°\\) to the full weight \\(mg\\) at \\(90°\\).' },
      { type: 'tf', q: 'Stretching a spring twice as far stores twice the elastic potential energy.',
        a: 'False. \\(U_s = \\tfrac{1}{2}k(\\Delta x)^2\\); doubling \\(\\Delta x\\) quadruples the stored energy.' },
      { type: 'tf', q: 'Gravitational field strength decreases as you move farther from Earth.',
        a: 'True. \\(g = GM/r^2\\) decreases with distance. At twice the radius, \\(g\\) is one-quarter as strong.' },
      { type: 'tf', q: 'The maximum static friction force is always greater than the kinetic friction force for the same surfaces.',
        a: 'True. Typically \\(\\mu_s > \\mu_k\\), so \\(\\mu_s F_n > \\mu_k F_n\\). It takes more force to start sliding than to keep sliding.' },
      { type: 'tf', q: 'Friction on an incline always acts down the slope.',
        a: 'False. Friction opposes relative motion or tendency of motion. If the object tends to slide down, friction acts up; if pushed up the slope, friction acts down.' },
    ]
  },
  'circular-motion': {
    title: 'Circular Motion',
    back: '../circular-motion/',
    cards: [
      { q: 'Centripetal acceleration',                      a: '\\[a_c = \\dfrac{v^2}{r}\\]',
        desc: '\\(v\\) = speed &nbsp;·&nbsp; \\(r\\) = radius; always directed inward' },
      { q: 'Net centripetal force',                         a: '\\[\\textstyle\\sum F_{\\text{rad}} = \\dfrac{mv^2}{r}\\]',
        desc: '\\(m\\) = mass &nbsp;·&nbsp; net inward component of all forces present' },
      { q: 'Period of circular motion',                     a: '\\[T = \\dfrac{2\\pi r}{v}\\]',
        desc: '\\(T\\) = time for one full revolution &nbsp;·&nbsp; \\(v\\) = speed' },
      { q: 'Frequency',                                     a: '\\[f = \\dfrac{1}{T}\\]',
        desc: '\\(f\\) = cycles per second (Hz) &nbsp;·&nbsp; \\(T\\) = period (s)' },
      { q: 'Orbital speed',                                 a: '\\[v^2 = \\dfrac{GM}{r}\\]',
        desc: '\\(G\\) = gravitational constant &nbsp;·&nbsp; \\(M\\) = central mass &nbsp;·&nbsp; \\(r\\) = orbital radius' },
      { q: "Kepler's 3rd law",                              a: '\\[T^2 = \\dfrac{4\\pi^2}{GM}\\,r^3\\]',
        desc: '\\(T\\) = period &nbsp;·&nbsp; \\(r\\) = orbital radius &nbsp;·&nbsp; \\(M\\) = central mass' },
      { type: 'tf', q: 'Centripetal force is a new fundamental force of nature, separate from gravity and tension.',
        a: 'False. "Centripetal force" is just the net inward component of forces already present (gravity, tension, normal force, etc.).' },
      { type: 'tf', q: 'An object in uniform circular motion has constant velocity.',
        a: 'False. Speed is constant, but the direction of velocity continuously changes, so velocity is not constant.' },
      { type: 'tf', q: 'If the orbital radius of a satellite doubles, its orbital period doubles.',
        a: 'False. By Kepler\'s 3rd law \\(T^2 \\propto r^3\\), so doubling \\(r\\) multiplies \\(T\\) by \\(2^{3/2} \\approx 2.83\\).' },
      { q: 'Centripetal acceleration in terms of period',     a: '\\[a_c = \\dfrac{4\\pi^2 r}{T^2}\\]',
        desc: 'substitute \\(v = 2\\pi r/T\\) into \\(a_c = v^2/r\\); useful when period is known' },
      { q: 'Minimum speed at top of a vertical loop',         a: '\\[v_{\\min} = \\sqrt{gr}\\]',
        desc: 'at this speed, gravity alone provides the centripetal force &nbsp;·&nbsp; \\(r\\) = loop radius' },
      { type: 'tf', q: 'A satellite in a stable circular orbit is constantly accelerating.',
        a: 'True. Gravity continuously deflects the satellite toward Earth. It "falls around" the planet — constant speed but changing direction means nonzero acceleration.' },
      { type: 'tf', q: 'Planets farther from the Sun have longer orbital periods.',
        a: 'True. Kepler\'s 3rd law: \\(T^2 \\propto r^3\\), so larger orbital radius gives a longer period.' },
      { type: 'tf', q: 'Doubling the radius of a circular path at constant speed doubles the centripetal acceleration.',
        a: 'False. \\(a_c = v^2/r\\); doubling \\(r\\) at constant \\(v\\) halves the centripetal acceleration.' },
      { type: 'tf', q: 'The orbital period of a satellite depends on its mass.',
        a: 'False. \\(T^2 = (4\\pi^2/GM)r^3\\) depends only on the central mass \\(M\\) and orbital radius \\(r\\), not the satellite\'s mass.' },
      { type: 'tf', q: 'A string is most likely to break at the bottom of a vertical circle, not the top.',
        a: 'True. At the bottom, tension must support the weight and provide centripetal force: \\(T = mv^2/r + mg\\). At the top, \\(T = mv^2/r - mg\\), which is smaller.' },
      { type: 'tf', q: 'Orbital speed increases as a satellite moves to a higher orbit.',
        a: 'False. \\(v = \\sqrt{GM/r}\\); larger \\(r\\) gives smaller \\(v\\). Higher orbits are slower.' },
      { type: 'tf', q: 'An object in uniform circular motion has constant speed but nonzero acceleration.',
        a: 'True. Speed is constant, but velocity direction continuously changes, so \\(\\vec{a} = \\Delta\\vec{v}/\\Delta t \\neq 0\\). Acceleration points toward the center.' },
    ]
  },
  'work-energy': {
    title: 'Work & Energy',
    back: '../work-energy/',
    cards: [
      { q: 'Kinetic energy',                                a: '\\[K = \\dfrac{1}{2}mv^2\\]',
        desc: '\\(m\\) = mass &nbsp;·&nbsp; \\(v\\) = speed; always non-negative' },
      { q: 'Work-energy theorem',                           a: '\\[W_{\\text{net}} = \\Delta K\\]',
        desc: 'net work done on an object equals its change in kinetic energy' },
      { q: 'Gravitational potential energy change',         a: '\\[\\Delta U_g = mg\\Delta y\\]',
        desc: '\\(\\Delta y\\) = height change (positive upward) &nbsp;·&nbsp; \\(g \\approx 9.8\\) m/s²' },
      { q: 'Spring potential energy',                       a: '\\[U_s = \\dfrac{1}{2}k(\\Delta x)^2\\]',
        desc: '\\(k\\) = spring constant &nbsp;·&nbsp; \\(\\Delta x\\) = stretch or compression' },
      { q: 'Mechanical energy',                             a: '\\[E_{\\text{mech}} = K + U\\]',
        desc: 'total of kinetic and potential energy' },
      { q: 'Conservation of energy (no external work or friction)',
                                                            a: '\\[\\Delta E_{\\text{mech}} = 0\\]',
        desc: 'holds when only conservative forces do work' },
      { q: 'Energy with friction or external work',         a: '\\[W_{\\text{ext}} = \\Delta E_{\\text{mech}} + \\Delta E_{\\text{th}}\\]',
        desc: '\\(W_\\text{ext}\\) = external work &nbsp;·&nbsp; \\(\\Delta E_\\text{th}\\) = thermal energy generated by friction' },
      { type: 'tf', q: 'A force perpendicular to an object\'s motion does zero work on it.',
        a: 'True. Work \\(= F\\,d\\cos\\theta\\). When \\(\\theta = 90°\\), \\(\\cos 90° = 0\\), so work is zero.' },
      { type: 'tf', q: 'If the net work done on an object is zero, the object must be at rest.',
        a: 'False. Zero net work means zero change in kinetic energy. The object can still be moving at constant speed.' },
      { type: 'tf', q: 'Potential energy can be negative.',
        a: 'True. PE depends on the chosen reference point. Gravitational PE \\(\\Delta U = mg\\Delta y\\) is negative below the reference, and the exact formula \\(U_g = -Gm_1m_2/r\\) is always negative.' },
      { q: 'Work done by a constant force',                   a: '\\[W = Fd\\cos\\theta\\]',
        desc: '\\(F\\) = force magnitude &nbsp;·&nbsp; \\(d\\) = displacement &nbsp;·&nbsp; \\(\\theta\\) = angle between \\(\\vec{F}\\) and \\(\\vec{d}\\)' },
      { q: 'Nonconservative work theorem',                    a: '\\[W_{\\text{nc}} = \\Delta E_{\\text{mech}}\\]',
        desc: 'nonconservative forces (friction, applied force) change mechanical energy &nbsp;·&nbsp; \\(W_\\text{nc} < 0\\) when friction does work' },
      { type: 'tf', q: 'The work done by gravity depends only on height change, not on the path taken.',
        a: 'True. Gravity is a conservative force. Work = \\(-mg\\Delta y\\), which depends only on vertical displacement.' },
      { type: 'tf', q: 'Doubling an object\'s kinetic energy doubles its speed.',
        a: 'False. \\(K = \\frac{1}{2}mv^2\\), so \\(v = \\sqrt{2K/m}\\). Doubling \\(K\\) multiplies speed by \\(\\sqrt{2} \\approx 1.41\\).' },
      { type: 'tf', q: 'A force applied perpendicular to an object\'s velocity can do no work.',
        a: 'True. Work \\(= \\vec{F}\\cdot\\vec{d} = Fd\\cos\\theta\\). At \\(\\theta = 90°\\), \\(W = 0\\). Normal force and centripetal force are examples.' },
      { type: 'tf', q: 'The work-energy theorem applies even when non-conservative forces act.',
        a: 'True. \\(W_{\\text{net}} = \\Delta K\\) always holds — it accounts for all forces, conservative or not.' },
      { type: 'tf', q: 'Friction violates conservation of energy.',
        a: 'False. Friction converts mechanical energy to thermal energy. Total energy is conserved; only mechanical energy decreases.' },
      { type: 'tf', q: 'A spring compressed by 2 cm stores four times the potential energy of one compressed by 1 cm.',
        a: 'True. \\(U_s = \\frac{1}{2}k(\\Delta x)^2\\). Doubling \\(\\Delta x\\) quadruples \\(U_s\\).' },
      { type: 'tf', q: 'Work done on an object can be negative.',
        a: 'True. If the force component along the displacement is opposite to the motion, \\(\\cos\\theta < 0\\) and work is negative (e.g., friction, drag).' },
      { q: 'Average power',                                   a: '\\[P_{\\text{avg}} = \\dfrac{W}{\\Delta t}\\]',
        desc: '\\(W\\) = work done (J) &nbsp;·&nbsp; \\(\\Delta t\\) = time interval (s) &nbsp;·&nbsp; units: watts (W = J/s)' },
      { q: 'Instantaneous power from force and velocity',     a: '\\[P = Fv\\cos\\theta\\]',
        desc: '\\(F\\) = force magnitude &nbsp;·&nbsp; \\(v\\) = speed &nbsp;·&nbsp; \\(\\theta\\) = angle between \\(\\vec{F}\\) and \\(\\vec{v}\\); simplifies to \\(P = Fv\\) when parallel' },
      { type: 'tf', q: 'A watt is equivalent to one joule per second.',
        a: 'True. By definition, \\(1\\,\\text{W} = 1\\,\\text{J/s}\\). Power measures the rate of energy transfer.' },
      { type: 'tf', q: 'A force perpendicular to an object\'s velocity delivers zero power.',
        a: 'True. \\(P = Fv\\cos\\theta\\). At \\(\\theta = 90°\\), \\(P = 0\\). Normal force and centripetal force do no work and deliver no power.' },
      { type: 'tf', q: 'Doubling the speed of an object doubles the power delivered by a constant parallel force.',
        a: 'True. \\(P = Fv\\), so doubling \\(v\\) at constant \\(F\\) doubles \\(P\\).' },
      { type: 'tf', q: 'Two machines that do the same total work always have the same power.',
        a: 'False. Power depends on how quickly the work is done: \\(P = W/\\Delta t\\). The same work done in half the time requires twice the power.' },
    ]
  },
  'momentum': {
    title: 'Impulse & Momentum',
    back: '../momentum/',
    cards: [
      { q: 'Linear momentum',                               a: '\\[\\vec{p} = m\\vec{v}\\]',
        desc: '\\(m\\) = mass (kg) &nbsp;·&nbsp; \\(\\vec{v}\\) = velocity; vector, units kg·m/s' },
      { q: "Newton's 2nd law (momentum form)",              a: '\\[\\vec{F}_{\\text{net}} = \\dfrac{\\Delta \\vec{p}}{\\Delta t}\\]',
        desc: 'net force equals the rate of change of momentum; reduces to \\(F = ma\\) for constant mass' },
      { q: 'Impulse',                                       a: '\\[\\vec{J} = \\vec{F}\\,\\Delta t\\]',
        desc: '\\(\\vec{F}\\) = (average) force &nbsp;·&nbsp; \\(\\Delta t\\) = contact time; area under the \\(F\\)-\\(t\\) curve' },
      { q: 'Impulse-momentum theorem',                      a: '\\[\\vec{J}_{\\text{net}} = \\Delta \\vec{p} = m\\vec{v}_f - m\\vec{v}_i\\]',
        desc: 'impulse from the net force equals the change in momentum' },
      { q: 'Conservation of momentum',                      a: '\\[\\textstyle\\sum \\vec{p}_i = \\sum \\vec{p}_f\\]',
        desc: 'holds when \\(\\vec{F}_{\\text{ext,net}} = 0\\); each component conserved separately' },
      { q: 'Two-body momentum conservation',                a: '\\[m_1\\vec{v}_{1i} + m_2\\vec{v}_{2i} = m_1\\vec{v}_{1f} + m_2\\vec{v}_{2f}\\]',
        desc: 'total momentum before equals total momentum after the interaction' },
      { q: 'Center of mass velocity',                       a: '\\[\\vec{v}_{\\text{cm}} = \\dfrac{\\vec{p}_{\\text{tot}}}{M}\\]',
        desc: '\\(M\\) = total mass; constant when no net external force acts' },
      { q: 'Kinetic energy from momentum',                  a: '\\[K = \\dfrac{p^2}{2m}\\]',
        desc: 'links the two quantities; same \\(p\\), smaller \\(m\\) means more \\(K\\)' },
      { type: 'tf', q: 'A truck and a bicycle with the same momentum have the same kinetic energy.',
        a: 'False. \\(K = p^2/2m\\), so for equal momentum the lighter object has more kinetic energy.' },
      { type: 'tf', q: 'Increasing the contact time of a collision reduces the average force for the same momentum change.',
        a: 'True. \\(F_{\\text{avg}} = \\Delta p / \\Delta t\\). This is why airbags and crumple zones work.' },
      { type: 'tf', q: 'Impulse and momentum have the same units.',
        a: 'True. \\(1\\,\\text{N·s} = 1\\,\\text{kg·m/s}\\), consistent with \\(\\vec{J} = \\Delta \\vec{p}\\).' },
      { type: 'tf', q: "An object's momentum can change even if its speed stays constant.",
        a: 'True. Momentum is a vector. In uniform circular motion the speed is constant but the direction, and therefore \\(\\vec{p}\\), continuously changes.' },
      { type: 'tf', q: "Internal forces can change a system's total momentum.",
        a: 'False. Internal forces come in action-reaction pairs whose impulses cancel. Only a net external force changes total momentum.' },
      { type: 'tf', q: 'Two objects that explode apart from rest have equal and opposite momenta.',
        a: 'True. Total momentum starts at zero and must stay zero, so \\(\\vec{p}_1 = -\\vec{p}_2\\).' },
      { type: 'tf', q: 'The center of mass of a system can be accelerated by internal forces.',
        a: 'False. \\(\\vec{F}_{\\text{ext,net}} = M\\vec{a}_{\\text{cm}}\\). Internal forces cancel in pairs and never move the center of mass.' },
      { type: 'tf', q: 'Momentum is a scalar quantity.',
        a: 'False. Momentum is a vector, \\(\\vec{p} = m\\vec{v}\\), with direction along the velocity. Components are conserved independently.' },
    ]
  },
  'collisions': {
    title: 'Collisions',
    back: '../collisions/',
    cards: [
      { q: 'Perfectly inelastic collision',       a: '\\[\\vec{v}_f = \\dfrac{m_1\\vec{v}_{1i} + m_2\\vec{v}_{2i}}{m_1 + m_2}\\]',
        desc: 'objects stick together and share one final velocity; maximum kinetic energy loss' },
      { q: 'Elastic 1D collision (target at rest)', a: '\\[v_{1f} = \\dfrac{m_1 - m_2}{m_1 + m_2}v_{1i} \\qquad v_{2f} = \\dfrac{2m_1}{m_1 + m_2}v_{1i}\\]',
        desc: 'both momentum and kinetic energy conserved' },
      { q: 'Lorentz factor',                      a: '\\[\\gamma = \\dfrac{1}{\\sqrt{1 - v^2/c^2}}\\]',
        desc: '\\(v\\) = particle speed &nbsp;·&nbsp; \\(c\\) = speed of light; \\(\\gamma \\approx 1\\) when \\(v \\ll c\\), grows without bound as \\(v \\to c\\)' },
      { q: 'Relativistic momentum',               a: '\\[\\vec{p} = \\gamma m\\vec{v}\\]',
        desc: 'reduces to \\(\\vec{p} = m\\vec{v}\\) at low speed; still a conserved vector quantity' },
      { q: 'Relativistic energy',                 a: '\\[E^2 = p^2c^2 + m^2c^4\\]',
        desc: '\\(p^2c^2\\) = contribution from motion &nbsp;·&nbsp; \\(m^2c^4\\) = contribution from mass; total \\(E\\) is conserved' },
      { q: 'Mass energy (particle at rest)',      a: '\\[E = mc^2\\]',
        desc: 'set \\(p = 0\\) in the relativistic energy equation; the energy an object has purely due to its mass' },
      { q: 'Massless particle (photon)',          a: '\\[E = pc \\implies p = E/c\\]',
        desc: 'set \\(m = 0\\); photons carry both energy and momentum despite having no mass' },
      { type: 'tf', q: 'Momentum is conserved in every type of collision, as long as no net external force acts.',
        a: 'True. Elastic, inelastic, and perfectly inelastic collisions all conserve total momentum. Only kinetic energy distinguishes them.' },
      { type: 'tf', q: 'Kinetic energy is conserved in all collisions.',
        a: 'False. Only elastic collisions conserve kinetic energy. Inelastic collisions convert some of it to heat, sound, and deformation.' },
      { type: 'tf', q: 'In an elastic collision between equal masses where one is at rest, the objects exchange velocities.',
        a: 'True. With \\(m_1 = m_2\\), the formulas give \\(v_{1f} = 0\\) and \\(v_{2f} = v_{1i}\\), like billiard balls.' },
      { type: 'tf', q: 'If two colliding objects separate more slowly than they approached, the collision was inelastic.',
        a: 'True. Elastic collisions preserve relative speed: \\(v_{1i} - v_{2i} = -(v_{1f} - v_{2f})\\). A slower separation means kinetic energy was lost.' },
      { type: 'tf', q: 'Momentum is conserved in high-energy particle collisions, in each dimension separately.',
        a: 'True. Physicists use this to detect "missing" momentum, which reveals undetected particles such as neutrinos.' },
      { type: 'tf', q: 'Mass is conserved in particle collisions.',
        a: 'False. Only total relativistic energy is conserved. Energy of motion can convert into the rest mass of new particles, which is why the LHC needs near-light speeds.' },
      { type: 'tf', q: 'Photons carry no momentum because they have no mass.',
        a: 'False. For massless particles \\(E = pc\\), so \\(p = E/c\\). Photons participate in both energy and momentum conservation.' },
    ]
  }
};
